2019-08-22 17:29:19,072 INFO: Microblog startup [in D:\myProject\education_proj\app\flask\microblog\app\__init__.py:44]
2019-08-22 17:29:37,667 ERROR: Exception on /edit_profile [POST] [in d:\myproject\education_proj\education_flask\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\myproject\education_proj\education_flask\lib\site-packages\sqlalchemy\engine\base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "d:\myproject\education_proj\education_flask\lib\site-packages\sqlalchemy\engine\default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\myproject\education_proj\education_flask\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\myproject\education_proj\education_flask\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\myproject\education_proj\education_flask\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\myproject\education_proj\education_flask\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\myproject\education_proj\education_flask\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\myproject\education_proj\education_flask\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\myproject\education_proj\education_flask\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\myProject\education_proj\app\flask\microblog\app\routes.py", line 98, in edit_profile
    db.session.commit()
  File "d:\myproject\education_proj\education_flask\lib\site-packages\sqlalchemy\orm\scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "d:\myproject\education_proj\education_flask\lib\site-packages\sqlalchemy\orm\session.py", line 1027, in commit
    self.transaction.commit()
  File "d:\myproject\education_proj\education_flask\lib\site-packages\sqlalchemy\orm\session.py", line 494, in commit
    self._prepare_impl()
  File "d:\myproject\education_proj\education_flask\lib\site-packages\sqlalchemy\orm\session.py", line 473, in _prepare_impl
    self.session.flush()
  File "d:\myproject\education_proj\education_flask\lib\site-packages\sqlalchemy\orm\session.py", line 2459, in flush
    self._flush(objects)
  File "d:\myproject\education_proj\education_flask\lib\site-packages\sqlalchemy\orm\session.py", line 2597, in _flush
    transaction.rollback(_capture_exception=True)
  File "d:\myproject\education_proj\education_flask\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "d:\myproject\education_proj\education_flask\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "d:\myproject\education_proj\education_flask\lib\site-packages\sqlalchemy\orm\session.py", line 2557, in _flush
    flush_context.execute()
  File "d:\myproject\education_proj\education_flask\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 422, in execute
    rec.execute(self)
  File "d:\myproject\education_proj\education_flask\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 589, in execute
    uow,
  File "d:\myproject\education_proj\education_flask\lib\site-packages\sqlalchemy\orm\persistence.py", line 236, in save_obj
    update,
  File "d:\myproject\education_proj\education_flask\lib\site-packages\sqlalchemy\orm\persistence.py", line 996, in _emit_update_statements
    statement, multiparams
  File "d:\myproject\education_proj\education_flask\lib\site-packages\sqlalchemy\engine\base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "d:\myproject\education_proj\education_flask\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "d:\myproject\education_proj\education_flask\lib\site-packages\sqlalchemy\engine\base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "d:\myproject\education_proj\education_flask\lib\site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "d:\myproject\education_proj\education_flask\lib\site-packages\sqlalchemy\engine\base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "d:\myproject\education_proj\education_flask\lib\site-packages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "d:\myproject\education_proj\education_flask\lib\site-packages\sqlalchemy\util\compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "d:\myproject\education_proj\education_flask\lib\site-packages\sqlalchemy\engine\base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "d:\myproject\education_proj\education_flask\lib\site-packages\sqlalchemy\engine\default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('Ñûí', '', 4)]
(Background on this error at: http://sqlalche.me/e/gkpj)
2019-08-22 17:33:23,080 INFO: Microblog startup [in D:\myProject\education_proj\app\flask\microblog\app\__init__.py:44]
2019-08-22 17:33:48,327 INFO: Microblog startup [in D:\myProject\education_proj\app\flask\microblog\app\__init__.py:44]
2019-08-26 14:45:22,720 INFO: Microblog startup [in D:\myProject\education_proj\app\flask\microblog\app\__init__.py:44]
2019-08-26 14:46:48,581 INFO: Microblog startup [in D:\myProject\education_proj\app\flask\microblog\app\__init__.py:44]
2019-08-26 14:47:06,871 INFO: Microblog startup [in D:\myProject\education_proj\app\flask\microblog\app\__init__.py:44]
2019-08-26 18:26:58,414 INFO: Microblog startup [in D:\myProject\education_proj\app\flask\microblog\app\__init__.py:44]
2019-08-26 18:29:40,554 INFO: Microblog startup [in D:\myProject\education_proj\app\flask\microblog\app\__init__.py:44]
2019-08-26 18:52:05,779 INFO: Microblog startup [in D:\myProject\education_proj\app\flask\microblog\app\__init__.py:44]
2019-08-26 18:57:20,060 INFO: Microblog startup [in D:\myProject\education_proj\app\flask\microblog\app\__init__.py:44]
2019-08-26 18:57:35,625 INFO: Microblog startup [in D:\myProject\education_proj\app\flask\microblog\app\__init__.py:44]
2019-08-28 12:10:54,776 INFO: Microblog startup [in D:\myProject\education_proj\app\flask\microblog\app\__init__.py:44]
2019-08-28 12:29:21,933 INFO: Microblog startup [in D:\myProject\education_proj\app\flask\microblog\app\__init__.py:44]
2019-08-28 12:29:33,047 INFO: Microblog startup [in D:\myProject\education_proj\app\flask\microblog\app\__init__.py:44]
2019-08-28 12:34:34,643 INFO: Microblog startup [in D:\myProject\education_proj\app\flask\microblog\app\__init__.py:44]
2019-08-28 13:05:29,191 INFO: Microblog startup [in D:\myProject\education_proj\app\flask\microblog\app\__init__.py:44]
2019-08-28 13:06:03,883 ERROR: Exception on /explore [GET] [in d:\myproject\education_proj\education_flask\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\myproject\education_proj\education_flask\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\myproject\education_proj\education_flask\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\myproject\education_proj\education_flask\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\myproject\education_proj\education_flask\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\myproject\education_proj\education_flask\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\myproject\education_proj\education_flask\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\myproject\education_proj\education_flask\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\myProject\education_proj\app\flask\microblog\app\routes.py", line 135, in explore
    posts = Post.query.order_by(Post.timestamp.desc()).paginate(page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
